---
- hosts: localhost
  connection: local
  gather_facts: no
#  become: yes
  vars:
    desired_state: present
  tasks:
    - name: deploy Flask container
#      docker_network:
#        name: web_dev
#      docker_volume:
#        name: dev_app
      docker_service:
        project_name: flask
        state: present
        restarted: yes
        build: yes
        definition:
          version: "3.5"
          networks: 
            web_net:
          services:
            web_dev:
              image: uav2608.flask:0.0.4
              ports:
                - "4000:4000"
              volumes:
                - ".:/app"
#              command: "/bin/bash"
#              command: "python index.py"
#          state: 
#            running: true
              environment:
                ENV: development
                PORT: 4000
                DB: mongodb://mongodb:27017/todoDev
      register: output    
    - debug: 
        var: 
          output
    - assert:
        that:
          - "web_dev.flask_web_dev_1.state.running"
      when: desired_state == "present"


