---
# tasks file for react-app

- name: Create WORKDIR (React)
  file:
    path: /{{dest_path}}
    state: directory
    owner: root
    group: root
    mode: 0775

- block:
  - name: Install tar, rsync and sudo (Alipne) (React)
    apk:
      name: "{{item}}"
      state: latest
      update_cache: yes
    loop:
      - tar
      - rsync
      - sudo
  when: ansible_os_family == "Alpine"

- block:
  - name: Install rsync and sudo (Debian) (React)
    apt:
      name: "{{item}}"
      state: present
    loop:
      - rsync
      - sudo
  when: ansible_facts['os_family'] == "Debian"

- block:
  - name: Install rsync and sudo (Centos) (React)
    yum:
      name: "{{item}}"
      state: present
    loop:
      - rsync
      - sudo
  when: ansible_facts['os_family'] == "RedHat"

- name: Synchronization with local folder (React)
  synchronize:
    src: /{{base_path}}/{{development_path}}/{{react_project_path}}/
    dest: /{{dest_path}}

