---
- hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  become: true
  vars_files:
    - ./vars/vagrant_packages.yaml

  tasks:

  - name: Install Packages
    yum: 
      name: "{{ item }}" 
      state: present
    loop: "{{ packages }}"

  - name: enable and start libvirtd
    systemd:
      name: libvirtd
      state: started
      enabled: yes

  - name: Add the current user to libvirt group
    user:
      name: "{{ ansible_user }}"
      groups: libvirt
      append: yes

  - name: Downloading packer
    get_url:
      url: https://releases.hashicorp.com/packer/1.3.5/packer_1.3.5_linux_amd64.zip
      dest: .
   
  - name: Unarchive packer
    unarchive:
      src: packer_1.3.5_linux_amd64.zip
      dest: /usr/local

  - name: Create link to packer
    file:
      src: /usr/local/packer 
      dest: /usr/local/bin/packer.io
      state: link

  - name: installing Vagrant
    yum:
      name: https://releases.hashicorp.com/vagrant/1.9.6/vagrant_1.9.6_x86_64.rpm 
      state: present

  - name: installing vagrant-libvirt plugin
    become: no
    shell: vagrant plugin install vagrant-libvirt

  - name: Install pip
    yum:
      name: python-pip
      state: present

  - name: installing Docker
    pip:
      name: docker-py

  - name: Install Docker Packages
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.5-3.1.el7.x86_64.rpm
      - https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-cli-18.09.5-3.el7.x86_64.rpm
#      - https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-selinux-17.03.3.ce-1.el7.noarch.rpm
      - https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-18.09.5-3.el7.x86_64.rpm

  - name: enable and start Docker
    systemd:
      name: docker
      state: started
      enabled: yes

  - name: Add the current user to docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes

