---
- name: Run using a project directory
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: react-compose
      vars:
         react_project_name  : todo-app1
#    - flask-service





