---
# Vagrant and Packer packages
vagrant_packages_centos: 
  - qemu-kvm
  - qemu-img
  - virt-manager
  - libvirt
  - libvirt-python
  - libvirt-client
  - virt-install
  - virt-viewer
  - bridge-utils
  - libguestfs-tools

vagrant_packages_debian:
  - qemu-kvm 
  - libvirt0
  - libvirt-clients 
  - libvirt-daemon-system 
  - bridge-utils 
  - libguestfs-tools 
  - genisoimage 
  - virtinst 
  - libosinfo-bin

kvm_packages2:
      - "https://cdimage.kali.org/kali-2019.1a/kali-linux-xfce-2019.1a-amd64.iso"
    
#current_user  : ansibleuser2
