---
- block:

  - name: Install Packages (Centos)
    yum:
      name: "{{ item }}"
      state: present
    loop: "{{ vagrant_packages_centos }}"

  when: ansible_os_family == "RedHat"


- block:

  - name: Install Packages (Debian)
    apt:
      name: "{{ item }}"
      state: present
    loop: "{{ vagrant_packages_debian }}"

  when: ansible_os_family == "Debian"


- name: enable and start libvirtd
  systemd:
      name: libvirtd
      state: started
      enabled: yes

- name: Add the current user to libvirt group
  user:
      name: "{{ item }}"
      groups: libvirt, libvirt-qemu
      append: yes
  loop:
    - "{{ ansible_user }}"
#    - "{{ current_user }}" 

- name: installing vagrant-libvirt plugin
  become: no
  shell: vagrant plugin install vagrant-libvirt

