---
# tasks file for flask-app

- name: Create WORKDIR (Flask)
  file:
    path: /{{dest_path}}
    state: directory
    owner: root
    group: root
    mode: 0775

- block:
  - name: Install tar, rsync and sudo (Alpine) (Flask) 
    apk:
       name: "{{item}}"
       state: present
       update_cache: yes
    loop:
       - rsync
       - sudo
       - tar     
  when: ansible_os_family == "Alpine"

- block:
  - name: Install rsync and sudo (Debian) (Flask)
    apt:
      name: "{{item}}"
      state: present
    loop:
      - rsync
      - sudo
  when: ansible_facts['os_family'] == "Debian"

- block:
  - name: Install rsync and sudo (Centos) (Flask)
    yum:
      name: "{{item}}"
      state: present
    loop:
      - rsync
      - sudo
  when: ansible_facts['os_family'] == "RedHat"

- name: Synchronization with local folder (Flask)
  synchronize:
    src: /{{base_path}}/{{development_path}}/{{flask_project_path}}/
    dest: /{{dest_path}}

- name: Install flask packages (Flask)
  shell: pip3.7 install -r /{{dest_path}}/requirements.txt
  register: pip_result
  until: pip_result is success
  retries: 5
  delay: 5

