---
- block:

  - name: downloading Vagrant (Centos)
    shell: wget https://releases.hashicorp.com/vagrant/{{vagrant_version}}/vagrant_{{vagrant_version}}_x86_64.rpm

  - name: Installing Vagrant (Centos)
    shell: yum install -y ./vagrant_{{vagrant_version}}_x86_64.rpm 

  - name: Removing Vagrant package (Centos)
    shell: rm ./vagrant_{{vagrant_version}}_86_64.rpm

  when: ansible_os_family == "RedHat"


- block:

#  - name: installing Vagrant (Debian)
#    apt:
#      name: https://releases.hashicorp.com/vagrant/{{vagrant_version}}/vagrant_{{vagrant_version}}_x86_64.deb
#      state: present

  - name: Downloading Vagrant (Debian)
    shell: wget https://releases.hashicorp.com/vagrant/{{vagrant_version}}/vagrant_{{vagrant_version}}_x86_64.deb

  - name: Installing Vagrant (Debian)
    shell: dpkg -i ./vagrant_{{vagrant_version}}_x86_64.deb

  - name: removing Vagrant package (Debian)
    shell: rm ./vagrant_{{vagrant_version}}_x86_64.deb

  when: ansible_os_family == "Debian"

