---
dist: xenial

language: python

services:
  - docker

node_js: 10

matrix:
  include:
    - name: "CentOS 7 Tests"
      env:
        - MOLECULE_DISTRO: centos7
    - name: "CentOS 6 Tests"
      env:
        - MOLECULE_DISTRO: centos6
    - name: "Ubuntu 18.04 Tests"
      env:
        - MOLECULE_DISTRO: ubuntu1804
    - name: "Ubuntu 16.04 Tests"
      env:
        - MOLECULE_DISTRO: ubuntu1604
    - name: "Ubuntu 14.04 Tests"
      env:
        - MOLECULE_DISTRO: ubuntu1404
    - name: "Debian 9 Tests"
      env:
        - MOLECULE_DISTRO: debian9
    - name: "Markdown test"
      install:
        # Install markdownlint and markdown-link-check
        - npm install -g markdownlint-cli markdown-link-check > /dev/null
      script:
        # Markdown check
        - find . -name "*.md" -print0 | xargs -0 markdownlint

        # Link Checks
        - find . -name "*.md" -print0 | xargs -0 markdown-link-check --quiet

install:
  # Install test dependencies.
  - pip install molecule docker

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
