# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "deb" do |deb|
    deb.vm.box = "debian/stretch64"
    deb.vm.hostname = 'debian'
    deb.vm.synced_folder "~/projects", "/usr/src/app", type: "rsync"

    deb.vm.network :private_network, ip: "192.168.121.101"

    deb.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "deb"]
    end

    deb.vm.provision "shell",
      inline: "sudo apt-get update -y && sudo apt-get install -y python"
    deb.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook_vagrant.yaml"
      ansible.verbose = true
      ansible.raw_arguments = ["--vault-id", "vault_pass"]
    end
  end

  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.hostname = 'centos'
    centos.vm.synced_folder "~/projects", "/usr/src/app", type: "rsync"

    centos.vm.network :private_network, ip: "192.168.121.102"

    centos.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "centos"]
    end

    centos.vm.provision "shell",
      inline: "sudo yum update -y && sudo yum install -y python"
    centos.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook_vagrant.yaml"
      ansible.verbose = true
      ansible.raw_arguments = ["--vault-id", "vault_pass"]
    end
  end
end
